sudo: false

language: php

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest TEST_PACKAGE="wp-cli/wp-cli-bundle wp-cli/wp-cli"
    - php: 7.0
      env: WP_VERSION=latest TEST_PACKAGE=commands
    - php: 7.0
      env: WP_VERSION=latest TEST_PACKAGE="wp-cli/wp-cli-bundle wp-cli/wp-cli" TEST_PHAR=nightly
    - php: 7.0
      env: WP_VERSION=latest TEST_PACKAGE=commands TEST_PHAR=nightly
    - php: 7.0
      env: WP_VERSION=latest TEST_PACKAGE="wp-cli/wp-cli-bundle wp-cli/wp-cli" TEST_PHAR=v2-nightly
    - php: 7.0
      env: WP_VERSION=latest TEST_PACKAGE=commands TEST_PHAR=v2-nightly

before_script:
  - ./ci/prepare.sh
  - composer prepare

script: ./ci/test.sh

cache:
  directories:
  - $HOME/.composer/cache

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: rPFmmApl0yOcaKmygce3Ha57symXtuPqTQXGf21W3DBDXU75TXKlxoGtVSmxgEebT9ZNl5S4CjVxwVRdph5BEUQYQs97wGMUY3ZIx+JZWiW6Md+QB34FIwJm7yYsDFFyvWzzuL/ZBju3YQ2vW9qs3geKfeUnnw34W6B4wsnLR3WAcb4PfroqlQ9BPzORI1QfYqsmqTBGc6piqVmxXLUgkIIKqMeXQVM7Qm6F2uAWRmWNWQqDGADyzelzc4Ws7r34U+H9I4m5kfnVMsX7vAFxVvtGV47stpa5QsEqz1JGvfPpV6gzvcQCaP1JbU2WPLD90TjWTygeRCm6eoLgM5GhcAiU7J+wNGJnoJY4ta0wo4PlMG6GObPiOVPvSWV3/FFBvhfd6iO4vxr44AjdLDyd9HgIn9TzCs6AvnXPva4yy0OiFHzQYFc7pFsMUEkW3hlQfjZciJbVvCLDB30RhXFkG4Yni3mcEkcogiwV0V620axBnudZD6URplmm+qRhU7damHMqVICXEh97frvl5RNC/S6BKtRLkTvIwMzpVPZCPS6tYNcctE34JeaqdN8bAhW7w2ddYoblRn3PdvAggtIPpWq7HGcBTUyrBOqxZOMUV54J1vWHK/8/W9FeufkXU2Xj1lXvrx+SS6ypwUjYmAbj+cnPyiSUwOD0iOo6oZArnjE=
      - secure: erUQQtYf3DQqi812np0My/yUjVOf0n2t+SxxTXA2Mu7nz2fyMqLeZw4unrzR2qnmcXqRFSAo9yygh1A2XZAW1Y2xJxYWUw7Q/+9L7SiuUUgpM6Bf2y/FFuNVsgeHc2HJdQAhgad++iodZtFSF5f3ueAVFCZaIyQ+MMuLPGbnWiNGPhG3Ek2St3FucrroPbgt25Ff6wXM2FKduxJPGIcdVD95FBjvvqwgla7y+LidQrFeOi73D2sl+O3UBfmOpX7BLxL9+cX5/KyuD3K5HvROyFBQwyegQWX+lHUqp+0I+LPk7I2MxQx9Y5aunln8Em+ZWjdId6hz7CgwQBEvDQVrcKcm18sJMBiYMSyvGofpkWo3KrcndoF7VZ7E4UCVXq/DYcXxAB+zEufAdkivv3tnwDrKzvR7eQPe8XgxW0K5/fHBADFFDRs5GQ2g6x5+Xu4w3bpkNtrXFT5Cv/P7O7AltZxMpGHadCmueaF/57D9pCKQBqYEXTB+ijIvsINZdNR4EECJxS0jLHb/EodY7kCh/zEP1fyfC1Ralc1sTU6zxioX4f3NHNV6uqYLje+c2Xkk3rQu4itL69YlC40QKlM54eHIBbPm7AiUzaKl+HpmoUZX8CWu0LnrEihnavdwY1zGqIkad3j5GdR7K3t4WiMxHa4YR2uuTWp7bN1JgrBHONw=
